spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: music-service
            uri: ${MUSIC_SERVICE_ROUTE_URI:http://localhost:8081}
            predicates:
              - Path=/api/songs/**


server:
  port: 8080
