spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/soa-authentication-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
  servlet:
    context-path: /api

keyStore:
  path: keystore.jks
  password: password
